apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "30 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron 
            image: miksveg/flask-app-demo:v3
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure