apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-deployment
  labels: 
    env: demo
spec:
  template:
    metadata:
      name: nginx
      labels: 
        env: demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      env: demo