apiVersion: v1
kind: Service
metadata: 
  namespace: ns1
  name: nodeport-service
  labels:
    env: demo
spec:
  type: NodePort
  selector:
    env: demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
