apiVersion: v1
kind: Pod
metadata:
  labels:
  name: db-pod
spec:
  containers:
  - image: redis
    name: db-pod-new
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disk
            operator: In
            values:
            - hdd